services:
  jupyter-notebook:
    build: 
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify your Dockerfile
    image: testing_cmds  # Optional: give your image a name
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 4G
    platform: linux/amd64