services:
  jupyter-notebook:
    image:  siddart/mds:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 4G
    platform: linux/amd64