services:
  jupyter-notebook:
    image: siddart/mds:41dd820
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 4G
    platform: linux/amd64
