name: academic-success-predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - altair=5.4.1
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - pandera=0.20.4
  - vl-convert-python=1.7.0
  - click=8.1.7
  - quarto=1.5.57
  - seaborn=0.13.2
  - requests=2.32.3
  - pytest=8.3.4